### ISSUE TITLE
php-fpm max children on fresh install

### ISSUE THREAD

**Issue by wiflye81** [freenas/iocage-plugin-nextcloud#11]
Hello,

On a fresh install of Nextcloud, I am getting 504 Gateway timeout in Nginx log.
After investigating, I found this line in php-fpm log:

[13-May-2019 12:48:55] WARNING: [pool nextcloud] server reached pm.max_children setting (5), consider raising it
After raising it to 15 and restart php-fpm service, Nextcloud is running more smoothly.

Please consider changing it to 10 as it improve the user experience.
I can make a PR for it.

Regards.

Gwenole

**Comment by miwi-fbsd** [comment]
Hi,

Yes I will raise that. Thanks.

**Comment by miwi-fbsd** [comment]
or so thanks :P
