### ISSUE TITLE
Nextcloud plugin NGINX configuration is out-of-date

### ISSUE THREAD

**Issue by ossama-othman** [freenas/iocage-plugin-nextcloud#16]
The Nextcloud plugin NGINX configuration is a bit out-of-date relative to the one recommended by the [Nextcloud 17 NGINX configuration documentation](https://docs.nextcloud.com/server/17/admin_manual/installation/nginx.html).

As far as I can tell, notable updates include:
  * re-enable gzip support
  * improve security
  * add workaround to known fastcgi PATH_INFO [issue](https://trac.nginx.org/nginx/ticket/321)
  * address some "Security & setup" warnings flagged in the Nextcloud admin user settings Overview page (e.g., maximum response age)
  * improve image asset handling

**Comment by miwi-fbsd** [comment]
Thank you for the submission. Much appreciated.
