### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by simonpie** [freenas/iocage-plugin-nextcloud#2]
Hello,

Right after installation, I set up the admin account and I am redirected to : http://10.0.1.83/index.php/apps/files/
But the page never loads and both Safari and Chrome complain that too many redirections happened.

I am running FreeNAS-11.2-BETA3.

**Comment by dlavigne** [comment]
Simon: the Nextcloud plugin is currently broken and slated to be fixed for RELEASE (it will be delisted for RC1). You can follow the progress of the plugin at https://redmine.ixsystems.com/issues/34162.

**Comment by dlavigne** [comment]
Yes. The ticket will give the URL to the PR for this repo.
