### ISSUE TITLE
Empty php-fpm PATH environment variable

### ISSUE THREAD

**Issue by adrido** [freenas/iocage-plugin-nextcloud#23]
In a fresh installation of nextclould, I still get the warning reported in #19 

PR #21 does not work, because the `env[...` lines from `www.conf` is actually `;env[` . They are commented out by default. So the grep command https://github.com/freenas/iocage-plugin-nextcloud/blob/master/post_install.sh#L44 does not find anything. So the Warning still exists.
I think `echo "env[PATH] = $PATH "` into `nextcloud.conf` would do it.

**Comment by kmoore134** [comment]
That sounds like it will fix it. Is that something you can open a pull request for us to review the fix?

**Comment by adrido** [comment]
Ill create a PR this weekend.
