### ISSUE TITLE
error when executing ´generate_letsencrypt_certificates´

### ISSUE THREAD

**Issue by adrido** [freenas/iocage-plugin-nextcloud#46]
I tried to follow the [instructions](https://github.com/freenas/iocage-plugin-nextcloud/tree/12.2-RELEASE) to get letsencrypt working again. 
but everything I get is the following error message.
```
iocage console nextcloud
[...]
root@nextcloud:~ # generate_letsencrypt_certificates "nextcloud.*****.net" "adr********.net"
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory_name ...
```

**Comment by suckerface** [comment]
Submitted PR ##47 to fix this command.
