### ISSUE TITLE
Can't update nextcloud into jail

### ISSUE THREAD

**Issue by diversunt** [freenas/iocage-plugin-nextcloud#49]
Hello! I am try update nextcloud using web updater and have error (look screen) 
![image](https://user-images.githubusercontent.com/38781759/141750453-9de8ef7a-0e84-4cdd-85a6-9c57d9bd3191.png)
If I'm deleting .htaccess.dist nextcloud is updating but after update "generate_letsencrypt_certificates"  isn't working.
How can I update nextcloud properly?

**Comment by artonge** [comment]
Can you be more specific on how `generate_letsencrypt_certificates` is failing ?

**Comment by diversunt** [comment]
After restart  are missing /usr/local/etc/letsencrypt/live/truenas folder
and 
"Renewal configuration file /usr/local/etc/letsencrypt/renewal/truenas.conf produced an unexpected error: expected /usr/local/etc/letsencrypt/live/truenas/cert.pem to be a symlink. Skipping.
Performing sanity check on nginx configuration:
nginx: [emerg] cannot load certificate "/usr/local/etc/letsencrypt/live/truenas/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/usr/local/etc/letsencrypt/live/truenas/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /usr/local/etc/nginx/nginx.conf test failed"
![image](https://user-images.githubusercontent.com/38781759/141816776-063a904a-97a7-4c11-a887-a9f94750a460.png)

**Comment by artonge** [comment]
Your certificates are generated with a `-000x` suffix.

Can you try to delete all the `truenas-000x` certificates and try again?

You can try to list the certificates that certbot find with the `certbot certificates` command and delete them one by one with `certbot delete <certificate-name>`. Simply deleting the files in `/etc/letsencrypt/live` and `/etc/letsencrypt/archive` should be enough.

**Comment by diversunt** [comment]
Hello, I'm reinstall jail and update one more time. All is good. Thank you everyone for help!
