### ISSUE TITLE
Unable to install or upgrade plugin

### ISSUE THREAD

**Issue by johnjaylward** [freenas/iocage-plugin-nextcloud#52]
It looks like the packages don't exist anymore for php74 upstream. Maybe it's just a fetch problem? This is causing the plugin upgrade and install to fail.

> Install
> 
> Error: nextcloud had a failure Exception: RuntimeError Message: pkg error: - nextcloud-php74 :,php74-pecl-imagick-im7 :,php74-bcmath :,php74-gmp :,php74-pcntl :,php74-pecl-redis : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

**Comment by funkybunch** [comment]
Source of the issue seems to be in a different repo.  Have a look at https://github.com/freenas/iocage-ix-plugins/issues/302

**Comment by johnjaylward** [comment]
I gave up and just made my own jail and installed what I needed

**Comment by sonicaj** [comment]
This has been resolved with https://github.com/freenas/iocage-ix-plugins/pull/304, if there are any other issues/concerns - please feel free to let us know. Thanks!
