### ISSUE TITLE
Can't install on either 11.2 RC1 or latest nightly

### ISSUE THREAD

**Issue by eitch** [freenas/iocage-plugin-nextcloud#6]
The legacy UI doesn't show me any plugins to install, and in the new UI it starts with:

    Release 11.2-RELEASE missing, will attempt to fetch it.

but then the following errors is shown:

    Exception: RuntimeError: Stopped nextcloud due to VNET failure occured, destroyed nextcloud.

I also tried the current release of FreeNas, but there the version was outdated. I'm new to FreeNas and am not sure if i am doing something wrong.

**Comment by dlavigne** [comment]
If you still have issues on RC2 (due out tomorrow), please create a ticket at bugs.freenas.org. Thanks!
