### ISSUE TITLE
occ warns about memory_limit is 128M, lower than 512M recommended

### ISSUE THREAD

**Issue by louizo** [freenas/iocage-plugin-nextcloud#9]
Fresh install of nextcloud,
starting occ warns about memory_limit=128M, below recommended value of 512M 

I'm writing a patch for this.

screenshot:
![2019-01-22_20-20-56](https://user-images.githubusercontent.com/12612524/51568562-48ff5280-1e9a-11e9-883c-60ae842aafc6.png)

**Comment by miwi-fbsd** [comment]
Thanks.
